import type { ParamKey } from './interfaces/ParamKey';
import type { ParamUnit } from './interfaces/ParamUnit';

/**
 * Единица каждого числа способностей — та же, что у его типа в `AbilityParams`. Типы значений
 * стираются при сборке, а описанию способности нужно знать, показать ли 0,6 как «60%».
 */
export const PARAM_UNITS: Readonly<Record<ParamKey, ParamUnit>> = {
  anyLine: 'count',
  armorBreak: 'ratio',
  blastMul: 'ratio',
  bleed: 'ratio',
  bleedTurns: 'turns',
  bossHpShare: 'ratio',
  bossPoison: 'ratio',
  burn: 'ratio',
  burstAt: 'count',
  burstMul: 'ratio',
  burstSplash: 'ratio',
  cap: 'ratio',
  chainPull: 'count',
  chargeMax: 'count',
  chargePer: 'ratio',
  charges: 'count',
  cross: 'count',
  debuffTurns: 'turns',
  defense: 'count',
  diagSplash: 'ratio',
  dmg: 'ratio',
  extraStrikes: 'count',
  falloff: 'ratio',
  freeze: 'ratio',
  freezeTurns: 'turns',
  holyDmg: 'ratio',
  hp: 'ratio',
  hpCost: 'ratio',
  hpLeft: 'count',
  hpPerResource: 'count',
  infect: 'ratio',
  limit: 'ratio',
  manaAbove: 'ratio',
  manaBonus: 'ratio',
  maxDelay: 'turns',
  maxStacks: 'count',
  perKill: 'ratio',
  perStack: 'ratio',
  pierce: 'count',
  poison: 'ratio',
  pullDmg: 'ratio',
  pullStun: 'turns',
  resource: 'count',
  shield: 'ratio',
  shockMul: 'count',
  splash: 'ratio',
  splashMul: 'ratio',
  spread: 'ratio',
  stepLoss: 'ratio',
  stun: 'turns',
  targets: 'count',
  thorns: 'ratio',
  ticks: 'turns',
  turns: 'turns',
  vuln: 'ratio',
  wallMul: 'count',
  weaken: 'ratio',
};
