export { HighHpDefense } from './defense/HighHpDefense';
export { KillStackDefense } from './defense/KillStackDefense';
export { KillTurnDefense } from './defense/KillTurnDefense';
export { ResourceDefense } from './defense/ResourceDefense';
export { ScarDefense } from './defense/ScarDefense';
export { ArmorToDamage } from './hero-damage/ArmorToDamage';
export { CarnageBonus } from './hero-damage/CarnageBonus';
export { GoldBonus } from './hero-damage/GoldBonus';
export { KillBonus } from './hero-damage/KillBonus';
export { RageBonus } from './hero-damage/RageBonus';
export type { DamageAcc } from './interfaces/DamageAcc';
export type { HeroView } from './interfaces/HeroView';
export type { IDamageReduction } from './interfaces/IDamageReduction';
export type { IDefenseModifier } from './interfaces/IDefenseModifier';
export type { IHeroDamageModifier } from './interfaces/IHeroDamageModifier';
export type { IncomingHit } from './interfaces/IncomingHit';
export type { ITargetDamageModifier } from './interfaces/ITargetDamageModifier';
export { BigHitReduction } from './reduction/BigHitReduction';
export { BossReduction } from './reduction/BossReduction';
export { FirstHitReduction } from './reduction/FirstHitReduction';
export { LowHpReduction } from './reduction/LowHpReduction';
export { MagicReduction } from './reduction/MagicReduction';
export { WoundedEnemyReduction } from './reduction/WoundedEnemyReduction';
export { BossBonus } from './target-damage/BossBonus';
export { FullHpBonus } from './target-damage/FullHpBonus';
export { LowHpBonus } from './target-damage/LowHpBonus';
