/**
 * Прибавки талантов: число за ранг прибавляется к характеристике или правилу героя
 * (проценты, очки, штуки — единицу знает сборка характеристик `buildPlayerStats`).
 */
export type TalentBonusFx =
  // ---- урон и способности (путь У)
  | 'dmgPct'
  | 'crit'
  | 'critMul'
  | 'perkPower'
  | 'artifactMul'
  | 'execute'
  | 'pierce'
  | 'doubleStrike'
  | 'overcharge'
  | 'lowHpDmg'
  | 'fullHpDmg'
  | 'bossDmg'
  | 'rageDmg'
  | 'goldDmg'
  | 'defDmg'
  | 'everyThird'
  // ---- здоровье и запас (путь З)
  | 'hpPct'
  | 'resMaxPct'
  | 'lowHpDr'
  | 'bigHitCut'
  | 'startShield'
  | 'potionPct'
  | 'cheatDeath'
  | 'revive'
  | 'killHp'
  | 'bossHp'
  | 'freePerk'
  | 'healShield'
  // ---- защита и ослабление врагов (путь Щ)
  | 'def'
  | 'parry'
  | 'dodge'
  | 'block'
  | 'thorns'
  | 'weaken'
  | 'firstHitDown'
  | 'armorBonus'
  | 'dotDr'
  | 'bossDr'
  | 'magicDr'
  | 'killDefTurn'
  | 'killDefStack'
  | 'roomGuard'
  | 'counterBuff'
  | 'highHpDef'
  | 'resDef'
  | 'perkDef'
  | 'scarDef'
  | 'manaShield';
